name: Deploy
on:
    workflow_dispatch:
    push:
        paths:
            - prisma/migrations/**
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
            - uses: pnpm/action-setup@v4
            - name: Install dependencies
              run: pnpm install
            - name: Apply all pending migrations to the database
              run: npx prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
