name: Deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
            - uses: pnpm/action-setup@v4
            - name: Install dependencies
              run: pnpm install
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      prisma:
                        - 'prisma/migrations/**'
            - name: Apply all pending migrations to the database
              if: steps.filter.outputs.prisma == 'true'
              run: npx prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
            - name: Trigger deployment
              run: |
                  curl -H 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' -H 'Content-Type: application/json' "https://host.rowmur.dev/api/v1/deploy?uuid=n8kss8swckkg4gwgoo4gs8os&force=false"
